name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  initialize:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup GraphQL
        run: ./gradlew downloadApolloSchema --endpoint="https://dads-engine.herokuapp.com" --schema="data/remote/src/commonMain/graphql/com/bael/dads/data/remote/schema.json"
      - name: Cache GraphQL setup
        uses: actions/cache@v2
        with:
          path: data/remote/src/commonMain/graphql/com/bael/dads/data/remote
          key: ${{ github.sha }}
  build:
    runs-on: macos-latest
    needs: initialize
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache GraphQL setup
        uses: actions/cache@v2
        with:
          path: data/remote/src/commonMain/graphql/com/bael/dads/data/remote
          key: ${{ github.sha }}
      - name: Build application
        run: ./gradlew assembleDebug --stacktrace
  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache GraphQL setup
        uses: actions/cache@v2
        with:
          path: data/remote/src/commonMain/graphql/com/bael/dads/data/remote
          key: ${{ github.sha }}
      - name: Test application
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport --stacktrace
      - name: Upload JaCoCo report
        uses: codecov/codecov-action@v1