name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  initialize:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Firebase
        run: openssl enc -aes-256-cbc -md sha256 -d -in app/google-services.enc -out app/google-services.json -k "$FIREBASE_SECRET"
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      - name: Setup GraphQL
        run: ./gradlew downloadApolloSchema --endpoint="https://dads-engine.herokuapp.com" --schema="libs/lib_remote/src/main/graphql/com/bael/dads/lib/remote/schema.json"
      - name: Cache Firebase setup
        uses: actions/cache@v2
        with:
          path: app
          key: ${{ hashFiles('app/google-services.enc') }}
      - name: Cache GraphQL setup
        uses: actions/cache@v2
        with:
          path: libs/lib_remote/src/main/graphql/com/bael/dads/lib/remote
          key: ${{ github.sha }}
  build:
    runs-on: macos-latest
    needs: initialize
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Firebase setup
        uses: actions/cache@v2
        with:
          path: app
          key: ${{ hashFiles('app/google-services.enc') }}
      - name: Cache GraphQL setup
        uses: actions/cache@v2
        with:
          path: libs/lib_remote/src/main/graphql/com/bael/dads/lib/remote
          key: ${{ github.sha }}
      - name: Build application
        run: ./gradlew assembleDebug --stacktrace
  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Firebase setup
        uses: actions/cache@v2
        with:
          path: app
          key: ${{ hashFiles('app/google-services.enc') }}
      - name: Cache GraphQL setup
        uses: actions/cache@v2
        with:
          path: libs/lib_remote/src/main/graphql/com/bael/dads/lib/remote
          key: ${{ github.sha }}
      - name: Test application
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport --stacktrace
      - name: Upload JaCoCo report
        uses: codecov/codecov-action@v1